#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - [ cd , /home/ubuntu ]
  - [ git, clone, "https://github.com/Benecoder/distributor.git"]
  - [ cd, distributor ]
  - [ chmod, +x, build_docker_image.sh ]
  - [ ./build_docker_image.sh ]
  - [ chmod, +x, gateway.sh ]
  - [ docker, pull, "openmined/grid-gateway:latest" ]
  - [ docker, pull, "openmined/grid-node:latest" ]

packages:
  - docker.io
  - docker-compose