#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - [ cd , /home/ubuntu ]
  - [ git, clone, "https://github.com/Benecoder/distributor.git"]
  - [ cd, distributor ]
  - [ chmod, +x, build_docker_image.sh ]
  - [ ./build_docker_image.sh ]
  - [ chmod, +x, gateway.sh ]
  - [ "./gatway.sh &"]

packages:
  - docker.io
  - docker-compose