version: '3'
services:
    gateway:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    redis:
        image: redis:latest
        expose:
        - 6379
        ports:
        - 6379:6379