version: '3'
services:
    gateway:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    redis:
        image: redis:latest
        expose:
        - 6379
        ports:
        - 6379:6379
    brutus:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://localhost:5000
                - ID=Brutus
                - ADDRESS=http://localhost:3000/
                - PORT=3000
        depends_on:
                - "redis"
        ports:
        - 3000:3000